name: zohelo_data
version: "1.0.0"
config-version: 2

profile: zohelo_data

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zohelo_data:
    bronze:
      +schema: 02_bronze
    silver:
      +schema: 03_silver
      +materialized: view
    gold:
      +schema: 04_gold
