{{ config(alias='dbw_observations', enabled=var('enable_gus_dbw', false)) }}

select
    cast(indicator_id as integer) as indicator_id,
    cast(przekroj_id as integer) as przekroj_id,
    cast(wymiar_1 as integer) as wymiar_1,
    cast(pozycja_1 as integer) as pozycja_1,
    cast(wymiar_2 as integer) as wymiar_2,
    cast(pozycja_2 as integer) as pozycja_2,
    cast(wymiar_3 as integer) as wymiar_3,
    cast(pozycja_3 as integer) as pozycja_3,
    cast(wymiar_4 as integer) as wymiar_4,
    cast(pozycja_4 as integer) as pozycja_4,
    cast(wymiar_5 as integer) as wymiar_5,
    cast(pozycja_5 as integer) as pozycja_5,
    cast(wymiar_6 as integer) as wymiar_6,
    cast(pozycja_6 as integer) as pozycja_6,
    cast(wymiar_7 as integer) as wymiar_7,
    cast(pozycja_7 as integer) as pozycja_7,
    cast(wymiar_8 as integer) as wymiar_8,
    cast(pozycja_8 as integer) as pozycja_8,
    cast(wymiar_9 as integer) as wymiar_9,
    cast(pozycja_9 as integer) as pozycja_9,
    cast(okres_id as integer) as okres_id,
    cast(sposob_prezentacji_miara_id as integer) as sposob_prezentacji_miara_id,
    cast(period_year as integer) as period_year,
    wartosc_raw,
    wartosc_numeric,
    cast(precyzja as integer) as precyzja,
    cast(brak_wartosci_id as integer) as brak_wartosci_id,
    cast(tajnosci_id as integer) as tajnosci_id,
    cast(flaga_id as integer) as flaga_id,
    raw_archive_file,
    source_row_number,
    processed_at_utc
from {{ ref('br_dbw_observations') }}
