{{ config(materialized=var('dbw_observations_materialization', 'table'), alias='dbw_observations', enabled=var('enable_gus_dbw', false)) }}
{{ assert_dbw_bronze_release() }}

select
    indicator_id,
    przekroj_id,
    wymiar_1,
    pozycja_1,
    wymiar_2,
    pozycja_2,
    wymiar_3,
    pozycja_3,
    wymiar_4,
    pozycja_4,
    wymiar_5,
    pozycja_5,
    wymiar_6,
    pozycja_6,
    wymiar_7,
    pozycja_7,
    wymiar_8,
    pozycja_8,
    wymiar_9,
    pozycja_9,
    okres_id,
    sposob_prezentacji_miara_id,
    period_year,
    wartosc_raw,
    wartosc_numeric,
    precyzja,
    brak_wartosci_id,
    tajnosci_id,
    flaga_id,
    raw_archive_file,
    source_row_number,
    processed_at_utc
from {{ source('bronze_dbw', 'observations') }}
